### ISSUE TITLE
Question: license.rdf creativecommons.org URL?

### ISSUE THREAD

**Issue by cgendreau** [creativecommons/license.rdf#2]
Is the license.rdf available on public creativecommons.org URL?

Regards

**Comment by csarven** [comment]
@cgendreau Are you looking for https://creativecommons.org/ns or https://creativecommons.org/schema.rdf ?

**Comment by cgendreau** [comment]
Sorry I can't recall exactly what I was trying to do and the description I wrote is not very verbose but I would say https://creativecommons.org/schema.rdf is probably what I was looking for.

I hope it was not at that location at the time otherwise sorry, my bad.
